const baseUrl = (process.env.AGENT_BASE_URL ?? "http://localhost:5000").replace(/\/$/, "");

async function readJson(res) {
  const text = await res.text();
  try {
    return JSON.parse(text);
  } catch {
    throw new Error(`Invalid JSON response (${res.status}): ${text}`);
  }
}

async function assertOk(res, context) {
  if (!res.ok) {
    const body = await res.text();
    throw new Error(`${context} failed (${res.status}): ${body}`);
  }
}

async function run() {
  console.log(`Agent smoke tests against ${baseUrl}`);

  const listRes = await fetch(`${baseUrl}/api/agents/packages`);
  await assertOk(listRes, "GET /api/agents/packages");
  const listPayload = await readJson(listRes);
  const beforeCount = Number(listPayload.count ?? 0);

  const workflow = {
    name: "smoke-pack",
    input: { hashtag: "react" },
    steps: [
      { type: "filter", field: "hashtag", operator: "includes", fromInput: "hashtag" },
      { type: "sort", by: "most-engagement" },
      { type: "limit", value: 5 },
    ],
  };

  const saveRes = await fetch(`${baseUrl}/api/agents/packages`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      slug: "smoke-pack",
      title: "Smoke Pack",
      description: "Generated by agent smoke test",
      workflowJson: JSON.stringify(workflow),
    }),
  });
  await assertOk(saveRes, "POST /api/agents/packages");
  const savePayload = await readJson(saveRes);
  if (savePayload?.package?.id !== "smoke-pack") {
    throw new Error("Saved package id mismatch");
  }

  const searchRes = await fetch(`${baseUrl}/api/agents/search?hashtag=react&sort=most-engagement&limit=5`);
  await assertOk(searchRes, "GET /api/agents/search");
  const searchPayload = await readJson(searchRes);
  if (!Array.isArray(searchPayload.results)) {
    throw new Error("Search response missing results array");
  }

  const runRes = await fetch(`${baseUrl}/api/agents/workflow`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ packageId: "smoke-pack", input: { hashtag: "react" } }),
  });
  await assertOk(runRes, "POST /api/agents/workflow");
  const runPayload = await readJson(runRes);
  if (!Array.isArray(runPayload.result)) {
    throw new Error("Workflow response missing result array");
  }

  const afterRes = await fetch(`${baseUrl}/api/agents/packages`);
  await assertOk(afterRes, "GET /api/agents/packages (after)");
  const afterPayload = await readJson(afterRes);
  const afterCount = Number(afterPayload.count ?? 0);

  console.log("Smoke summary", {
    packagesBefore: beforeCount,
    packagesAfter: afterCount,
    searchResults: searchPayload.results.length,
    workflowResults: runPayload.result.length,
  });
}

run().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
